image: node:18

pipelines:
  custom:
    scheduled-tests:
      - step:
          name: Run Selenium Tests
          caches:
            - node
          script:
            - apt-get update
            - apt-get install -y wget unzip xvfb
            - npm ci
            - npm run test:ci
            - cat test-report.html || true

  schedules:
    - cron: '*/30 * * * *'
      pipeline: custom/scheduled-tests
      enabled: true
